//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS_SkyScraper.MrBillService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.profile.octagroup.com", ConfigurationName="MrBillService.MrBillServicePortType")]
    public interface MrBillServicePortType {
        
        // CODEGEN: Generating message contract since message getMrBillUsersWithoutSuppliersRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersResponse getMrBillUsersWithoutSuppliers(SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersResponse> getMrBillUsersWithoutSuppliersAsync(SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersRequest request);
        
        // CODEGEN: Generating message contract since message getMrBillUsersRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAS_SkyScraper.MrBillService.getMrBillUsersResponse getMrBillUsers(SAS_SkyScraper.MrBillService.getMrBillUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SAS_SkyScraper.MrBillService.getMrBillUsersResponse> getMrBillUsersAsync(SAS_SkyScraper.MrBillService.getMrBillUsersRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://security.profile.octagroup.com")]
    public partial class AuthenticationToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.profile.octagroup.com")]
    public partial class Transaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime addedDateField;
        
        private bool addedDateFieldSpecified;
        
        private string attachedPersonsField;
        
        private string bookingReferenceField;
        
        private string categoryField;
        
        private string countryField;
        
        private string creditCardNumberField;
        
        private string creditCardOwnerField;
        
        private string currencyField;
        
        private System.DateTime date1Field;
        
        private bool date1FieldSpecified;
        
        private System.DateTime date2Field;
        
        private bool date2FieldSpecified;
        
        private string departureCityField;
        
        private string descriptionField;
        
        private string destinationField;
        
        private string destinationCityField;
        
        private System.DateTime expenseDateField;
        
        private bool expenseDateFieldSpecified;
        
        private string fileLocationField;
        
        private System.Nullable<long> idField;
        
        private bool idFieldSpecified;
        
        private System.Nullable<decimal> localAmountField;
        
        private bool localAmountFieldSpecified;
        
        private string multiTransactionIdField;
        
        private System.Nullable<int> numberOfUnitsField;
        
        private bool numberOfUnitsFieldSpecified;
        
        private string paymentTypeField;
        
        private bool prePaidField;
        
        private bool prePaidFieldSpecified;
        
        private System.Nullable<decimal> priceField;
        
        private bool priceFieldSpecified;
        
        private string productField;
        
        private System.DateTime removedDateField;
        
        private bool removedDateFieldSpecified;
        
        private bool toBeDeletedField;
        
        private bool toBeDeletedFieldSpecified;
        
        private System.Nullable<decimal> totalField;
        
        private bool totalFieldSpecified;
        
        private System.DateTime transactionDateField;
        
        private string transactionOwnerField;
        
        private TransactionStatus transactionStatusField;
        
        private string transactionSupplierField;
        
        private string travelerConfirmationEmailField;
        
        private string travelerCostCenterField;
        
        private string travelerEmployeeIdField;
        
        private string travelerMembershipCardField;
        
        private string travelerNameField;
        
        private string travelerProjectNumberField;
        
        private string tripTypeField;
        
        private Identity userIdentityField;
        
        private string userTypeField;
        
        private System.Nullable<decimal> vat1Field;
        
        private bool vat1FieldSpecified;
        
        private System.Nullable<decimal> vat2Field;
        
        private bool vat2FieldSpecified;
        
        private System.Nullable<decimal> vat3Field;
        
        private bool vat3FieldSpecified;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime addedDate {
            get {
                return this.addedDateField;
            }
            set {
                this.addedDateField = value;
                this.RaisePropertyChanged("addedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool addedDateSpecified {
            get {
                return this.addedDateFieldSpecified;
            }
            set {
                this.addedDateFieldSpecified = value;
                this.RaisePropertyChanged("addedDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string attachedPersons {
            get {
                return this.attachedPersonsField;
            }
            set {
                this.attachedPersonsField = value;
                this.RaisePropertyChanged("attachedPersons");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string bookingReference {
            get {
                return this.bookingReferenceField;
            }
            set {
                this.bookingReferenceField = value;
                this.RaisePropertyChanged("bookingReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string creditCardNumber {
            get {
                return this.creditCardNumberField;
            }
            set {
                this.creditCardNumberField = value;
                this.RaisePropertyChanged("creditCardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string creditCardOwner {
            get {
                return this.creditCardOwnerField;
            }
            set {
                this.creditCardOwnerField = value;
                this.RaisePropertyChanged("creditCardOwner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime date1 {
            get {
                return this.date1Field;
            }
            set {
                this.date1Field = value;
                this.RaisePropertyChanged("date1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool date1Specified {
            get {
                return this.date1FieldSpecified;
            }
            set {
                this.date1FieldSpecified = value;
                this.RaisePropertyChanged("date1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime date2 {
            get {
                return this.date2Field;
            }
            set {
                this.date2Field = value;
                this.RaisePropertyChanged("date2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool date2Specified {
            get {
                return this.date2FieldSpecified;
            }
            set {
                this.date2FieldSpecified = value;
                this.RaisePropertyChanged("date2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string departureCity {
            get {
                return this.departureCityField;
            }
            set {
                this.departureCityField = value;
                this.RaisePropertyChanged("departureCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string destinationCity {
            get {
                return this.destinationCityField;
            }
            set {
                this.destinationCityField = value;
                this.RaisePropertyChanged("destinationCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime expenseDate {
            get {
                return this.expenseDateField;
            }
            set {
                this.expenseDateField = value;
                this.RaisePropertyChanged("expenseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expenseDateSpecified {
            get {
                return this.expenseDateFieldSpecified;
            }
            set {
                this.expenseDateFieldSpecified = value;
                this.RaisePropertyChanged("expenseDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string fileLocation {
            get {
                return this.fileLocationField;
            }
            set {
                this.fileLocationField = value;
                this.RaisePropertyChanged("fileLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<long> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<decimal> localAmount {
            get {
                return this.localAmountField;
            }
            set {
                this.localAmountField = value;
                this.RaisePropertyChanged("localAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localAmountSpecified {
            get {
                return this.localAmountFieldSpecified;
            }
            set {
                this.localAmountFieldSpecified = value;
                this.RaisePropertyChanged("localAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string multiTransactionId {
            get {
                return this.multiTransactionIdField;
            }
            set {
                this.multiTransactionIdField = value;
                this.RaisePropertyChanged("multiTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<int> numberOfUnits {
            get {
                return this.numberOfUnitsField;
            }
            set {
                this.numberOfUnitsField = value;
                this.RaisePropertyChanged("numberOfUnits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberOfUnitsSpecified {
            get {
                return this.numberOfUnitsFieldSpecified;
            }
            set {
                this.numberOfUnitsFieldSpecified = value;
                this.RaisePropertyChanged("numberOfUnitsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string paymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("paymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool prePaid {
            get {
                return this.prePaidField;
            }
            set {
                this.prePaidField = value;
                this.RaisePropertyChanged("prePaid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prePaidSpecified {
            get {
                return this.prePaidFieldSpecified;
            }
            set {
                this.prePaidFieldSpecified = value;
                this.RaisePropertyChanged("prePaidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<decimal> price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("product");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public System.DateTime removedDate {
            get {
                return this.removedDateField;
            }
            set {
                this.removedDateField = value;
                this.RaisePropertyChanged("removedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool removedDateSpecified {
            get {
                return this.removedDateFieldSpecified;
            }
            set {
                this.removedDateFieldSpecified = value;
                this.RaisePropertyChanged("removedDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public bool toBeDeleted {
            get {
                return this.toBeDeletedField;
            }
            set {
                this.toBeDeletedField = value;
                this.RaisePropertyChanged("toBeDeleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toBeDeletedSpecified {
            get {
                return this.toBeDeletedFieldSpecified;
            }
            set {
                this.toBeDeletedFieldSpecified = value;
                this.RaisePropertyChanged("toBeDeletedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public System.Nullable<decimal> total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
                this.RaisePropertyChanged("totalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("transactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string transactionOwner {
            get {
                return this.transactionOwnerField;
            }
            set {
                this.transactionOwnerField = value;
                this.RaisePropertyChanged("transactionOwner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public TransactionStatus transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
                this.RaisePropertyChanged("transactionStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string transactionSupplier {
            get {
                return this.transactionSupplierField;
            }
            set {
                this.transactionSupplierField = value;
                this.RaisePropertyChanged("transactionSupplier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string travelerConfirmationEmail {
            get {
                return this.travelerConfirmationEmailField;
            }
            set {
                this.travelerConfirmationEmailField = value;
                this.RaisePropertyChanged("travelerConfirmationEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string travelerCostCenter {
            get {
                return this.travelerCostCenterField;
            }
            set {
                this.travelerCostCenterField = value;
                this.RaisePropertyChanged("travelerCostCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string travelerEmployeeId {
            get {
                return this.travelerEmployeeIdField;
            }
            set {
                this.travelerEmployeeIdField = value;
                this.RaisePropertyChanged("travelerEmployeeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public string travelerMembershipCard {
            get {
                return this.travelerMembershipCardField;
            }
            set {
                this.travelerMembershipCardField = value;
                this.RaisePropertyChanged("travelerMembershipCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public string travelerName {
            get {
                return this.travelerNameField;
            }
            set {
                this.travelerNameField = value;
                this.RaisePropertyChanged("travelerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public string travelerProjectNumber {
            get {
                return this.travelerProjectNumberField;
            }
            set {
                this.travelerProjectNumberField = value;
                this.RaisePropertyChanged("travelerProjectNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public string tripType {
            get {
                return this.tripTypeField;
            }
            set {
                this.tripTypeField = value;
                this.RaisePropertyChanged("tripType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public Identity userIdentity {
            get {
                return this.userIdentityField;
            }
            set {
                this.userIdentityField = value;
                this.RaisePropertyChanged("userIdentity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public string userType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
                this.RaisePropertyChanged("userType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public System.Nullable<decimal> vat1 {
            get {
                return this.vat1Field;
            }
            set {
                this.vat1Field = value;
                this.RaisePropertyChanged("vat1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vat1Specified {
            get {
                return this.vat1FieldSpecified;
            }
            set {
                this.vat1FieldSpecified = value;
                this.RaisePropertyChanged("vat1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public System.Nullable<decimal> vat2 {
            get {
                return this.vat2Field;
            }
            set {
                this.vat2Field = value;
                this.RaisePropertyChanged("vat2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vat2Specified {
            get {
                return this.vat2FieldSpecified;
            }
            set {
                this.vat2FieldSpecified = value;
                this.RaisePropertyChanged("vat2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public System.Nullable<decimal> vat3 {
            get {
                return this.vat3Field;
            }
            set {
                this.vat3Field = value;
                this.RaisePropertyChanged("vat3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vat3Specified {
            get {
                return this.vat3FieldSpecified;
            }
            set {
                this.vat3FieldSpecified = value;
                this.RaisePropertyChanged("vat3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.profile.octagroup.com")]
    public enum TransactionStatus {
        
        /// <remarks/>
        SHOWN,
        
        /// <remarks/>
        HIDDEN,
        
        /// <remarks/>
        DISABLED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.profile.octagroup.com")]
    public partial class Identity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.profile.octagroup.com")]
    public partial class TransactionSupplier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string supplierPasswordField;
        
        private string supplierUsernameField;
        
        private bool toBeDeletedField;
        
        private bool toBeDeletedFieldSpecified;
        
        private string urlField;
        
        private Identity userIdentityField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string supplierPassword {
            get {
                return this.supplierPasswordField;
            }
            set {
                this.supplierPasswordField = value;
                this.RaisePropertyChanged("supplierPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string supplierUsername {
            get {
                return this.supplierUsernameField;
            }
            set {
                this.supplierUsernameField = value;
                this.RaisePropertyChanged("supplierUsername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool toBeDeleted {
            get {
                return this.toBeDeletedField;
            }
            set {
                this.toBeDeletedField = value;
                this.RaisePropertyChanged("toBeDeleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toBeDeletedSpecified {
            get {
                return this.toBeDeletedFieldSpecified;
            }
            set {
                this.toBeDeletedFieldSpecified = value;
                this.RaisePropertyChanged("toBeDeletedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public Identity userIdentity {
            get {
                return this.userIdentityField;
            }
            set {
                this.userIdentityField = value;
                this.RaisePropertyChanged("userIdentity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.profile.octagroup.com")]
    public partial class MrBillDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TransactionSupplier[] transactionSuppliersField;
        
        private Transaction[] transactionsField;
        
        private System.Nullable<long> userIdField;
        
        private bool userIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://model.profile.octagroup.com")]
        public TransactionSupplier[] transactionSuppliers {
            get {
                return this.transactionSuppliersField;
            }
            set {
                this.transactionSuppliersField = value;
                this.RaisePropertyChanged("transactionSuppliers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://model.profile.octagroup.com")]
        public Transaction[] transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("transactions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userIdSpecified {
            get {
                return this.userIdFieldSpecified;
            }
            set {
                this.userIdFieldSpecified = value;
                this.RaisePropertyChanged("userIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.profile.octagroup.com")]
    public partial class ContactInfoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string mobileField;
        
        private System.Nullable<long> userIdField;
        
        private bool userIdFieldSpecified;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userIdSpecified {
            get {
                return this.userIdFieldSpecified;
            }
            set {
                this.userIdFieldSpecified = value;
                this.RaisePropertyChanged("userIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMrBillUsersWithoutSuppliers", WrapperNamespace="http://service.profile.octagroup.com", IsWrapped=true)]
    public partial class getMrBillUsersWithoutSuppliersRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.profile.octagroup.com")]
        public SAS_SkyScraper.MrBillService.AuthenticationToken AuthenticationToken;
        
        public getMrBillUsersWithoutSuppliersRequest() {
        }
        
        public getMrBillUsersWithoutSuppliersRequest(SAS_SkyScraper.MrBillService.AuthenticationToken AuthenticationToken) {
            this.AuthenticationToken = AuthenticationToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMrBillUsersWithoutSuppliersResponse", WrapperNamespace="http://service.profile.octagroup.com", IsWrapped=true)]
    public partial class getMrBillUsersWithoutSuppliersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.profile.octagroup.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://dto.model.profile.octagroup.com")]
        public SAS_SkyScraper.MrBillService.ContactInfoDTO[] @out;
        
        public getMrBillUsersWithoutSuppliersResponse() {
        }
        
        public getMrBillUsersWithoutSuppliersResponse(SAS_SkyScraper.MrBillService.ContactInfoDTO[] @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMrBillUsers", WrapperNamespace="http://service.profile.octagroup.com", IsWrapped=true)]
    public partial class getMrBillUsersRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.profile.octagroup.com")]
        public SAS_SkyScraper.MrBillService.AuthenticationToken AuthenticationToken;
        
        public getMrBillUsersRequest() {
        }
        
        public getMrBillUsersRequest(SAS_SkyScraper.MrBillService.AuthenticationToken AuthenticationToken) {
            this.AuthenticationToken = AuthenticationToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMrBillUsersResponse", WrapperNamespace="http://service.profile.octagroup.com", IsWrapped=true)]
    public partial class getMrBillUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.profile.octagroup.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://dto.model.profile.octagroup.com")]
        public SAS_SkyScraper.MrBillService.MrBillDTO[] @out;
        
        public getMrBillUsersResponse() {
        }
        
        public getMrBillUsersResponse(SAS_SkyScraper.MrBillService.MrBillDTO[] @out) {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MrBillServicePortTypeChannel : SAS_SkyScraper.MrBillService.MrBillServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MrBillServicePortTypeClient : System.ServiceModel.ClientBase<SAS_SkyScraper.MrBillService.MrBillServicePortType>, SAS_SkyScraper.MrBillService.MrBillServicePortType {
        
        public MrBillServicePortTypeClient() {
        }
        
        public MrBillServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MrBillServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MrBillServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MrBillServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersResponse SAS_SkyScraper.MrBillService.MrBillServicePortType.getMrBillUsersWithoutSuppliers(SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersRequest request) {
            return base.Channel.getMrBillUsersWithoutSuppliers(request);
        }
        
        public SAS_SkyScraper.MrBillService.ContactInfoDTO[] getMrBillUsersWithoutSuppliers(SAS_SkyScraper.MrBillService.AuthenticationToken AuthenticationToken) {
            SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersRequest inValue = new SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersRequest();
            inValue.AuthenticationToken = AuthenticationToken;
            SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersResponse retVal = ((SAS_SkyScraper.MrBillService.MrBillServicePortType)(this)).getMrBillUsersWithoutSuppliers(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersResponse> SAS_SkyScraper.MrBillService.MrBillServicePortType.getMrBillUsersWithoutSuppliersAsync(SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersRequest request) {
            return base.Channel.getMrBillUsersWithoutSuppliersAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersResponse> getMrBillUsersWithoutSuppliersAsync(SAS_SkyScraper.MrBillService.AuthenticationToken AuthenticationToken) {
            SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersRequest inValue = new SAS_SkyScraper.MrBillService.getMrBillUsersWithoutSuppliersRequest();
            inValue.AuthenticationToken = AuthenticationToken;
            return ((SAS_SkyScraper.MrBillService.MrBillServicePortType)(this)).getMrBillUsersWithoutSuppliersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAS_SkyScraper.MrBillService.getMrBillUsersResponse SAS_SkyScraper.MrBillService.MrBillServicePortType.getMrBillUsers(SAS_SkyScraper.MrBillService.getMrBillUsersRequest request) {
            return base.Channel.getMrBillUsers(request);
        }
        
        public SAS_SkyScraper.MrBillService.MrBillDTO[] getMrBillUsers(SAS_SkyScraper.MrBillService.AuthenticationToken AuthenticationToken) {
            SAS_SkyScraper.MrBillService.getMrBillUsersRequest inValue = new SAS_SkyScraper.MrBillService.getMrBillUsersRequest();
            inValue.AuthenticationToken = AuthenticationToken;
            SAS_SkyScraper.MrBillService.getMrBillUsersResponse retVal = ((SAS_SkyScraper.MrBillService.MrBillServicePortType)(this)).getMrBillUsers(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAS_SkyScraper.MrBillService.getMrBillUsersResponse> SAS_SkyScraper.MrBillService.MrBillServicePortType.getMrBillUsersAsync(SAS_SkyScraper.MrBillService.getMrBillUsersRequest request) {
            return base.Channel.getMrBillUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAS_SkyScraper.MrBillService.getMrBillUsersResponse> getMrBillUsersAsync(SAS_SkyScraper.MrBillService.AuthenticationToken AuthenticationToken) {
            SAS_SkyScraper.MrBillService.getMrBillUsersRequest inValue = new SAS_SkyScraper.MrBillService.getMrBillUsersRequest();
            inValue.AuthenticationToken = AuthenticationToken;
            return ((SAS_SkyScraper.MrBillService.MrBillServicePortType)(this)).getMrBillUsersAsync(inValue);
        }
    }
}
