//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrBill_MVC.MrBillUserServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/MrBillServices.DTO")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MrBill_MVC.MrBillUserServices.CompanyInfoDTO CompanyInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserRoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MrBill_MVC.MrBillUserServices.UserRolesDTO UserRolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MrBill_MVC.MrBillUserServices.UserSupplierInfoDTO[] UserSupplierInfoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MrBill_MVC.MrBillUserServices.CompanyInfoDTO CompanyInfo {
            get {
                return this.CompanyInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyInfoField, value) != true)) {
                    this.CompanyInfoField = value;
                    this.RaisePropertyChanged("CompanyInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserRoleId {
            get {
                return this.UserRoleIdField;
            }
            set {
                if ((this.UserRoleIdField.Equals(value) != true)) {
                    this.UserRoleIdField = value;
                    this.RaisePropertyChanged("UserRoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MrBill_MVC.MrBillUserServices.UserRolesDTO UserRoles {
            get {
                return this.UserRolesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRolesField, value) != true)) {
                    this.UserRolesField = value;
                    this.RaisePropertyChanged("UserRoles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MrBill_MVC.MrBillUserServices.UserSupplierInfoDTO[] UserSupplierInfoes {
            get {
                return this.UserSupplierInfoesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSupplierInfoesField, value) != true)) {
                    this.UserSupplierInfoesField = value;
                    this.RaisePropertyChanged("UserSupplierInfoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/MrBillServices.DTO")]
    [System.SerializableAttribute()]
    public partial class CompanyInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VATCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VATCode {
            get {
                return this.VATCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VATCodeField, value) != true)) {
                    this.VATCodeField = value;
                    this.RaisePropertyChanged("VATCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRolesDTO", Namespace="http://schemas.datacontract.org/2004/07/MrBillServices.DTO")]
    [System.SerializableAttribute()]
    public partial class UserRolesDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSupplierInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/MrBillServices.DTO")]
    [System.SerializableAttribute()]
    public partial class UserSupplierInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupplierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MrBill_MVC.MrBillUserServices.SupplierInfoDTO SupplierInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MrBill_MVC.MrBillUserServices.SupplierInfoDTO SupplierInfo {
            get {
                return this.SupplierInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierInfoField, value) != true)) {
                    this.SupplierInfoField = value;
                    this.RaisePropertyChanged("SupplierInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/MrBillServices.DTO")]
    [System.SerializableAttribute()]
    public partial class SupplierInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResetPasswordUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignUpUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupplierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResetPasswordUrl {
            get {
                return this.ResetPasswordUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ResetPasswordUrlField, value) != true)) {
                    this.ResetPasswordUrlField = value;
                    this.RaisePropertyChanged("ResetPasswordUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignUpUrl {
            get {
                return this.SignUpUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SignUpUrlField, value) != true)) {
                    this.SignUpUrlField = value;
                    this.RaisePropertyChanged("SignUpUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SettingDTO", Namespace="http://schemas.datacontract.org/2004/07/MrBillServices.DTO")]
    [System.SerializableAttribute()]
    public partial class SettingDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SettingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SettingValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettingName {
            get {
                return this.SettingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SettingNameField, value) != true)) {
                    this.SettingNameField = value;
                    this.RaisePropertyChanged("SettingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettingValue {
            get {
                return this.SettingValueField;
            }
            set {
                if ((object.ReferenceEquals(this.SettingValueField, value) != true)) {
                    this.SettingValueField = value;
                    this.RaisePropertyChanged("SettingValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MrBillUserServices.IMrBillUserServices")]
    public interface IMrBillUserServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/CreateUser", ReplyAction="http://tempuri.org/IMrBillUserServices/CreateUserResponse")]
        int CreateUser(MrBill_MVC.MrBillUserServices.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/CreateUser", ReplyAction="http://tempuri.org/IMrBillUserServices/CreateUserResponse")]
        System.Threading.Tasks.Task<int> CreateUserAsync(MrBill_MVC.MrBillUserServices.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/UpdateUser", ReplyAction="http://tempuri.org/IMrBillUserServices/UpdateUserResponse")]
        int UpdateUser(string token, MrBill_MVC.MrBillUserServices.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/UpdateUser", ReplyAction="http://tempuri.org/IMrBillUserServices/UpdateUserResponse")]
        System.Threading.Tasks.Task<int> UpdateUserAsync(string token, MrBill_MVC.MrBillUserServices.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetUserByUsername", ReplyAction="http://tempuri.org/IMrBillUserServices/GetUserByUsernameResponse")]
        MrBill_MVC.MrBillUserServices.UserDTO GetUserByUsername(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetUserByUsername", ReplyAction="http://tempuri.org/IMrBillUserServices/GetUserByUsernameResponse")]
        System.Threading.Tasks.Task<MrBill_MVC.MrBillUserServices.UserDTO> GetUserByUsernameAsync(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetUserIDByUsername", ReplyAction="http://tempuri.org/IMrBillUserServices/GetUserIDByUsernameResponse")]
        int GetUserIDByUsername(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetUserIDByUsername", ReplyAction="http://tempuri.org/IMrBillUserServices/GetUserIDByUsernameResponse")]
        System.Threading.Tasks.Task<int> GetUserIDByUsernameAsync(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetAllSupplierInfoList", ReplyAction="http://tempuri.org/IMrBillUserServices/GetAllSupplierInfoListResponse")]
        MrBill_MVC.MrBillUserServices.SupplierInfoDTO[] GetAllSupplierInfoList(string token, string username, bool includeOtherSupplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetAllSupplierInfoList", ReplyAction="http://tempuri.org/IMrBillUserServices/GetAllSupplierInfoListResponse")]
        System.Threading.Tasks.Task<MrBill_MVC.MrBillUserServices.SupplierInfoDTO[]> GetAllSupplierInfoListAsync(string token, string username, bool includeOtherSupplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/AddOrUpdateSetting", ReplyAction="http://tempuri.org/IMrBillUserServices/AddOrUpdateSettingResponse")]
        string AddOrUpdateSetting(string token, string username, MrBill_MVC.MrBillUserServices.SettingDTO settingDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/AddOrUpdateSetting", ReplyAction="http://tempuri.org/IMrBillUserServices/AddOrUpdateSettingResponse")]
        System.Threading.Tasks.Task<string> AddOrUpdateSettingAsync(string token, string username, MrBill_MVC.MrBillUserServices.SettingDTO settingDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetSetingById", ReplyAction="http://tempuri.org/IMrBillUserServices/GetSetingByIdResponse")]
        MrBill_MVC.MrBillUserServices.SettingDTO GetSetingById(string token, string username, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetSetingById", ReplyAction="http://tempuri.org/IMrBillUserServices/GetSetingByIdResponse")]
        System.Threading.Tasks.Task<MrBill_MVC.MrBillUserServices.SettingDTO> GetSetingByIdAsync(string token, string username, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/IsSuperAdmin", ReplyAction="http://tempuri.org/IMrBillUserServices/IsSuperAdminResponse")]
        bool IsSuperAdmin(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/IsSuperAdmin", ReplyAction="http://tempuri.org/IMrBillUserServices/IsSuperAdminResponse")]
        System.Threading.Tasks.Task<bool> IsSuperAdminAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/IsAdmin", ReplyAction="http://tempuri.org/IMrBillUserServices/IsAdminResponse")]
        bool IsAdmin(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/IsAdmin", ReplyAction="http://tempuri.org/IMrBillUserServices/IsAdminResponse")]
        System.Threading.Tasks.Task<bool> IsAdminAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetAllMessage", ReplyAction="http://tempuri.org/IMrBillUserServices/GetAllMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MrBill_MVC.MrBillUserServices.UserDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MrBill_MVC.MrBillUserServices.CompanyInfoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MrBill_MVC.MrBillUserServices.UserRolesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MrBill_MVC.MrBillUserServices.UserSupplierInfoDTO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MrBill_MVC.MrBillUserServices.UserSupplierInfoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MrBill_MVC.MrBillUserServices.SupplierInfoDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MrBill_MVC.MrBillUserServices.SupplierInfoDTO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MrBill_MVC.MrBillUserServices.SettingDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MrBill_MVC.MrBillUserServices.UserDTO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] GetAllMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetAllMessage", ReplyAction="http://tempuri.org/IMrBillUserServices/GetAllMessageResponse")]
        System.Threading.Tasks.Task<object[]> GetAllMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetAllUser", ReplyAction="http://tempuri.org/IMrBillUserServices/GetAllUserResponse")]
        MrBill_MVC.MrBillUserServices.UserDTO[] GetAllUser(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetAllUser", ReplyAction="http://tempuri.org/IMrBillUserServices/GetAllUserResponse")]
        System.Threading.Tasks.Task<MrBill_MVC.MrBillUserServices.UserDTO[]> GetAllUserAsync(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetAllUserSupplierInfo", ReplyAction="http://tempuri.org/IMrBillUserServices/GetAllUserSupplierInfoResponse")]
        MrBill_MVC.MrBillUserServices.UserSupplierInfoDTO[] GetAllUserSupplierInfo(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillUserServices/GetAllUserSupplierInfo", ReplyAction="http://tempuri.org/IMrBillUserServices/GetAllUserSupplierInfoResponse")]
        System.Threading.Tasks.Task<MrBill_MVC.MrBillUserServices.UserSupplierInfoDTO[]> GetAllUserSupplierInfoAsync(string token, string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMrBillUserServicesChannel : MrBill_MVC.MrBillUserServices.IMrBillUserServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MrBillUserServicesClient : System.ServiceModel.ClientBase<MrBill_MVC.MrBillUserServices.IMrBillUserServices>, MrBill_MVC.MrBillUserServices.IMrBillUserServices {
        
        public MrBillUserServicesClient() {
        }
        
        public MrBillUserServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MrBillUserServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MrBillUserServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MrBillUserServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateUser(MrBill_MVC.MrBillUserServices.UserDTO user) {
            return base.Channel.CreateUser(user);
        }
        
        public System.Threading.Tasks.Task<int> CreateUserAsync(MrBill_MVC.MrBillUserServices.UserDTO user) {
            return base.Channel.CreateUserAsync(user);
        }
        
        public int UpdateUser(string token, MrBill_MVC.MrBillUserServices.UserDTO user) {
            return base.Channel.UpdateUser(token, user);
        }
        
        public System.Threading.Tasks.Task<int> UpdateUserAsync(string token, MrBill_MVC.MrBillUserServices.UserDTO user) {
            return base.Channel.UpdateUserAsync(token, user);
        }
        
        public MrBill_MVC.MrBillUserServices.UserDTO GetUserByUsername(string token, string username) {
            return base.Channel.GetUserByUsername(token, username);
        }
        
        public System.Threading.Tasks.Task<MrBill_MVC.MrBillUserServices.UserDTO> GetUserByUsernameAsync(string token, string username) {
            return base.Channel.GetUserByUsernameAsync(token, username);
        }
        
        public int GetUserIDByUsername(string token, string username) {
            return base.Channel.GetUserIDByUsername(token, username);
        }
        
        public System.Threading.Tasks.Task<int> GetUserIDByUsernameAsync(string token, string username) {
            return base.Channel.GetUserIDByUsernameAsync(token, username);
        }
        
        public MrBill_MVC.MrBillUserServices.SupplierInfoDTO[] GetAllSupplierInfoList(string token, string username, bool includeOtherSupplier) {
            return base.Channel.GetAllSupplierInfoList(token, username, includeOtherSupplier);
        }
        
        public System.Threading.Tasks.Task<MrBill_MVC.MrBillUserServices.SupplierInfoDTO[]> GetAllSupplierInfoListAsync(string token, string username, bool includeOtherSupplier) {
            return base.Channel.GetAllSupplierInfoListAsync(token, username, includeOtherSupplier);
        }
        
        public string AddOrUpdateSetting(string token, string username, MrBill_MVC.MrBillUserServices.SettingDTO settingDto) {
            return base.Channel.AddOrUpdateSetting(token, username, settingDto);
        }
        
        public System.Threading.Tasks.Task<string> AddOrUpdateSettingAsync(string token, string username, MrBill_MVC.MrBillUserServices.SettingDTO settingDto) {
            return base.Channel.AddOrUpdateSettingAsync(token, username, settingDto);
        }
        
        public MrBill_MVC.MrBillUserServices.SettingDTO GetSetingById(string token, string username, int userId) {
            return base.Channel.GetSetingById(token, username, userId);
        }
        
        public System.Threading.Tasks.Task<MrBill_MVC.MrBillUserServices.SettingDTO> GetSetingByIdAsync(string token, string username, int userId) {
            return base.Channel.GetSetingByIdAsync(token, username, userId);
        }
        
        public bool IsSuperAdmin(int userId) {
            return base.Channel.IsSuperAdmin(userId);
        }
        
        public System.Threading.Tasks.Task<bool> IsSuperAdminAsync(int userId) {
            return base.Channel.IsSuperAdminAsync(userId);
        }
        
        public bool IsAdmin(int userId) {
            return base.Channel.IsAdmin(userId);
        }
        
        public System.Threading.Tasks.Task<bool> IsAdminAsync(int userId) {
            return base.Channel.IsAdminAsync(userId);
        }
        
        public object[] GetAllMessage() {
            return base.Channel.GetAllMessage();
        }
        
        public System.Threading.Tasks.Task<object[]> GetAllMessageAsync() {
            return base.Channel.GetAllMessageAsync();
        }
        
        public MrBill_MVC.MrBillUserServices.UserDTO[] GetAllUser(string token, string username) {
            return base.Channel.GetAllUser(token, username);
        }
        
        public System.Threading.Tasks.Task<MrBill_MVC.MrBillUserServices.UserDTO[]> GetAllUserAsync(string token, string username) {
            return base.Channel.GetAllUserAsync(token, username);
        }
        
        public MrBill_MVC.MrBillUserServices.UserSupplierInfoDTO[] GetAllUserSupplierInfo(string token, string username) {
            return base.Channel.GetAllUserSupplierInfo(token, username);
        }
        
        public System.Threading.Tasks.Task<MrBill_MVC.MrBillUserServices.UserSupplierInfoDTO[]> GetAllUserSupplierInfoAsync(string token, string username) {
            return base.Channel.GetAllUserSupplierInfoAsync(token, username);
        }
    }
}
