//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scraper.MrBillServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MrBillDTO", Namespace="http://schemas.datacontract.org/2004/07/MrBillServices.DTO")]
    [System.SerializableAttribute()]
    public partial class MrBillDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Scraper.MrBillServices.UserSupplierdata[] UserSupplierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Scraper.MrBillServices.UserSupplierdata[] UserSupplier {
            get {
                return this.UserSupplierField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSupplierField, value) != true)) {
                    this.UserSupplierField = value;
                    this.RaisePropertyChanged("UserSupplier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSupplierdata", Namespace="http://schemas.datacontract.org/2004/07/MrBillServices.DTO")]
    [System.SerializableAttribute()]
    public partial class UserSupplierdata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupplierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierPassword {
            get {
                return this.SupplierPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierPasswordField, value) != true)) {
                    this.SupplierPasswordField = value;
                    this.RaisePropertyChanged("SupplierPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierUsername {
            get {
                return this.SupplierUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierUsernameField, value) != true)) {
                    this.SupplierUsernameField = value;
                    this.RaisePropertyChanged("SupplierUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/MrBillServices.DTO")]
    [System.SerializableAttribute()]
    public partial class SupplierInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResetPasswordUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignUpUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupplierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResetPasswordUrl {
            get {
                return this.ResetPasswordUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ResetPasswordUrlField, value) != true)) {
                    this.ResetPasswordUrlField = value;
                    this.RaisePropertyChanged("ResetPasswordUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignUpUrl {
            get {
                return this.SignUpUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SignUpUrlField, value) != true)) {
                    this.SignUpUrlField = value;
                    this.RaisePropertyChanged("SignUpUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/MrBillServices.DTO")]
    [System.SerializableAttribute()]
    public partial class ContactInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MrBillServices.IMrBillServices")]
    public interface IMrBillServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/GetMrBillUsers", ReplyAction="http://tempuri.org/IMrBillServices/GetMrBillUsersResponse")]
        Scraper.MrBillServices.MrBillDTO[] GetMrBillUsers(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/GetMrBillUsers", ReplyAction="http://tempuri.org/IMrBillServices/GetMrBillUsersResponse")]
        System.Threading.Tasks.Task<Scraper.MrBillServices.MrBillDTO[]> GetMrBillUsersAsync(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/GetSupplierByListId", ReplyAction="http://tempuri.org/IMrBillServices/GetSupplierByListIdResponse")]
        Scraper.MrBillServices.SupplierInfoDTO[] GetSupplierByListId(string token, string username, int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/GetSupplierByListId", ReplyAction="http://tempuri.org/IMrBillServices/GetSupplierByListIdResponse")]
        System.Threading.Tasks.Task<Scraper.MrBillServices.SupplierInfoDTO[]> GetSupplierByListIdAsync(string token, string username, int[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/GetMrBillUsersWithoutSuppliers", ReplyAction="http://tempuri.org/IMrBillServices/GetMrBillUsersWithoutSuppliersResponse")]
        Scraper.MrBillServices.ContactInfoDTO[] GetMrBillUsersWithoutSuppliers(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/GetMrBillUsersWithoutSuppliers", ReplyAction="http://tempuri.org/IMrBillServices/GetMrBillUsersWithoutSuppliersResponse")]
        System.Threading.Tasks.Task<Scraper.MrBillServices.ContactInfoDTO[]> GetMrBillUsersWithoutSuppliersAsync(string token, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/testConnection", ReplyAction="http://tempuri.org/IMrBillServices/testConnectionResponse")]
        int testConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/testConnection", ReplyAction="http://tempuri.org/IMrBillServices/testConnectionResponse")]
        System.Threading.Tasks.Task<int> testConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/SendEmailReport", ReplyAction="http://tempuri.org/IMrBillServices/SendEmailReportResponse")]
        bool SendEmailReport(string username, string[] emailList, int month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/SendEmailReport", ReplyAction="http://tempuri.org/IMrBillServices/SendEmailReportResponse")]
        System.Threading.Tasks.Task<bool> SendEmailReportAsync(string username, string[] emailList, int month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/pdfReview", ReplyAction="http://tempuri.org/IMrBillServices/pdfReviewResponse")]
        string pdfReview(string username, int month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/pdfReview", ReplyAction="http://tempuri.org/IMrBillServices/pdfReviewResponse")]
        System.Threading.Tasks.Task<string> pdfReviewAsync(string username, int month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/DownloadReport", ReplyAction="http://tempuri.org/IMrBillServices/DownloadReportResponse")]
        byte[] DownloadReport(string username, string[] emailList, int month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/DownloadReport", ReplyAction="http://tempuri.org/IMrBillServices/DownloadReportResponse")]
        System.Threading.Tasks.Task<byte[]> DownloadReportAsync(string username, string[] emailList, int month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/WriteScraperLog", ReplyAction="http://tempuri.org/IMrBillServices/WriteScraperLogResponse")]
        string WriteScraperLog(System.Nullable<int> type, System.Nullable<int> userId, System.Nullable<int> supplierId, string message, System.DateTime time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMrBillServices/WriteScraperLog", ReplyAction="http://tempuri.org/IMrBillServices/WriteScraperLogResponse")]
        System.Threading.Tasks.Task<string> WriteScraperLogAsync(System.Nullable<int> type, System.Nullable<int> userId, System.Nullable<int> supplierId, string message, System.DateTime time);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMrBillServicesChannel : Scraper.MrBillServices.IMrBillServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MrBillServicesClient : System.ServiceModel.ClientBase<Scraper.MrBillServices.IMrBillServices>, Scraper.MrBillServices.IMrBillServices {
        
        public MrBillServicesClient() {
        }
        
        public MrBillServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MrBillServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MrBillServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MrBillServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Scraper.MrBillServices.MrBillDTO[] GetMrBillUsers(string token, string username) {
            return base.Channel.GetMrBillUsers(token, username);
        }
        
        public System.Threading.Tasks.Task<Scraper.MrBillServices.MrBillDTO[]> GetMrBillUsersAsync(string token, string username) {
            return base.Channel.GetMrBillUsersAsync(token, username);
        }
        
        public Scraper.MrBillServices.SupplierInfoDTO[] GetSupplierByListId(string token, string username, int[] ids) {
            return base.Channel.GetSupplierByListId(token, username, ids);
        }
        
        public System.Threading.Tasks.Task<Scraper.MrBillServices.SupplierInfoDTO[]> GetSupplierByListIdAsync(string token, string username, int[] ids) {
            return base.Channel.GetSupplierByListIdAsync(token, username, ids);
        }
        
        public Scraper.MrBillServices.ContactInfoDTO[] GetMrBillUsersWithoutSuppliers(string token, string username) {
            return base.Channel.GetMrBillUsersWithoutSuppliers(token, username);
        }
        
        public System.Threading.Tasks.Task<Scraper.MrBillServices.ContactInfoDTO[]> GetMrBillUsersWithoutSuppliersAsync(string token, string username) {
            return base.Channel.GetMrBillUsersWithoutSuppliersAsync(token, username);
        }
        
        public int testConnection() {
            return base.Channel.testConnection();
        }
        
        public System.Threading.Tasks.Task<int> testConnectionAsync() {
            return base.Channel.testConnectionAsync();
        }
        
        public bool SendEmailReport(string username, string[] emailList, int month, int year) {
            return base.Channel.SendEmailReport(username, emailList, month, year);
        }
        
        public System.Threading.Tasks.Task<bool> SendEmailReportAsync(string username, string[] emailList, int month, int year) {
            return base.Channel.SendEmailReportAsync(username, emailList, month, year);
        }
        
        public string pdfReview(string username, int month, int year) {
            return base.Channel.pdfReview(username, month, year);
        }
        
        public System.Threading.Tasks.Task<string> pdfReviewAsync(string username, int month, int year) {
            return base.Channel.pdfReviewAsync(username, month, year);
        }
        
        public byte[] DownloadReport(string username, string[] emailList, int month, int year) {
            return base.Channel.DownloadReport(username, emailList, month, year);
        }
        
        public System.Threading.Tasks.Task<byte[]> DownloadReportAsync(string username, string[] emailList, int month, int year) {
            return base.Channel.DownloadReportAsync(username, emailList, month, year);
        }
        
        public string WriteScraperLog(System.Nullable<int> type, System.Nullable<int> userId, System.Nullable<int> supplierId, string message, System.DateTime time) {
            return base.Channel.WriteScraperLog(type, userId, supplierId, message, time);
        }
        
        public System.Threading.Tasks.Task<string> WriteScraperLogAsync(System.Nullable<int> type, System.Nullable<int> userId, System.Nullable<int> supplierId, string message, System.DateTime time) {
            return base.Channel.WriteScraperLogAsync(type, userId, supplierId, message, time);
        }
    }
}
