//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrBillServices.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public CompanyInfo()
        {
            this.CompanyInfo1 = new HashSet<CompanyInfo>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string VatCode { get; set; }
        public Nullable<int> RootCompanyID { get; set; }
    
        public virtual ICollection<CompanyInfo> CompanyInfo1 { get; set; }
        public virtual CompanyInfo CompanyInfo2 { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
