//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrBillServices.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInfo
    {
        public SupplierInfo()
        {
            this.UserSupplierInfoes = new HashSet<UserSupplierInfo>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int SupplierID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string SignUpUrl { get; set; }
        public string ResetPasswordUrl { get; set; }
    
        public virtual ICollection<UserSupplierInfo> UserSupplierInfoes { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
