//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrBillServices.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public string BookingRef { get; set; }
        public string Description { get; set; }
        public string Destination { get; set; }
        public string Traveller { get; set; }
        public Nullable<System.DateTime> HtlTime1 { get; set; }
        public Nullable<System.DateTime> HtlTime2 { get; set; }
        public Nullable<System.DateTime> AirDepTime1 { get; set; }
        public Nullable<System.DateTime> AirDepTime2 { get; set; }
        public Nullable<System.DateTime> AirRetTime1 { get; set; }
        public Nullable<System.DateTime> AirRetTime2 { get; set; }
        public Nullable<System.DateTime> CarTime1 { get; set; }
        public Nullable<System.DateTime> CarTime2 { get; set; }
        public string Country { get; set; }
        public string CityDep1 { get; set; }
        public string CityDep2 { get; set; }
        public string CityRet1 { get; set; }
        public string CityRet2 { get; set; }
        public string Product { get; set; }
        public Nullable<float> Price { get; set; }
        public Nullable<float> PriceUserCurrency { get; set; }
        public Nullable<float> Total { get; set; }
        public Nullable<float> Vat1 { get; set; }
        public Nullable<float> Vat2 { get; set; }
        public Nullable<float> Vat3 { get; set; }
        public Nullable<int> Units { get; set; }
        public string PriceCurrency { get; set; }
        public string CardNumber { get; set; }
        public string CardHolder { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> RemoveDate { get; set; }
        public string ExtraInfo { get; set; }
        public string Attendees { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public int ExportStatus { get; set; }
        public Nullable<System.DateTime> UnlockedDate { get; set; }
        public Nullable<int> UnlockedBy { get; set; }
        public int CategoryID { get; set; }
        public int UserID { get; set; }
        public int PaymentID { get; set; }
        public Nullable<int> TransactionGroupID { get; set; }
        public int SupplierID { get; set; }
        public Nullable<int> CostCenter { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ProjectNO { get; set; }
        public string ReceiptLink { get; set; }
        public Nullable<int> MainTrip { get; set; }
    
        public virtual CostCenter CostCenter1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Project Project { get; set; }
        public virtual SupplierInfo SupplierInfo { get; set; }
        public virtual TripCategory TripCategory { get; set; }
        public virtual TransactionGroup TransactionGroup { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
